name: Print Secret Example

on:
  push:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Access secret
        run: |
          echo "Secret value is: $MY_SECRET_KEY"
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
